const WORDS_A2 = [
  { id: 1, en: "Sky", tr: "Gökyüzü" },
  { id: 2, en: "Wood", tr: "Ağaçlık" },
  { id: 3, en: "Hill", tr: "Tepe" },
  { id: 4, en: "Farmer", tr: "Çiftçi" },
  { id: 5, en: "Valley", tr: "Vadi" },
  { id: 6, en: "Tree", tr: "Ağaç" },
  { id: 7, en: "Field", tr: "Alan / Tarla" },
  { id: 8, en: "Farm", tr: "Çiftlik" },
  { id: 9, en: "Lake", tr: "Göl" },
  { id: 10, en: "Horse", tr: "At" },
  { id: 11, en: "Boat", tr: "Kayık" },
  { id: 12, en: "Grass", tr: "Çimen" },
  { id: 13, en: "Dog", tr: "Köpek" },
  { id: 14, en: "Path", tr: "Patika / Keçi Yolu" },
  { id: 15, en: "Grow", tr: "Büyü(t)mek / Yetiş(tir)mek" },
  { id: 16, en: "Own", tr: "Sahip Olmak" },
  { id: 17, en: "Crop", tr: "Mahsul" },
  { id: 18, en: "Area", tr: "Alan / Bölge" },
  { id: 19, en: "Countryside", tr: "Kırsal Bölge" },
  { id: 20, en: "Bird", tr: "Kuş" },
  { id: 21, en: "Wonderful", tr: "Harika" },
  { id: 22, en: "Fresh Food", tr: "Taze Yiyecek" },
  { id: 23, en: "Healthy", tr: "Sağlıklı" },
  { id: 24, en: "Public Transport", tr: "Toplu Taşıma" },
  { id: 25, en: "Terrible", tr: "Korkunç" },
  { id: 26, en: "Ride a Bike", tr: "Bisiklete Binmek" },
  { id: 27, en: "Alone", tr: "Yalnız" },
  { id: 28, en: "Lonely", tr: "Yalnız Bir Şekilde" },
  { id: 29, en: "Look After", tr: "İlgilenmek" },
  { id: 30, en: "Market", tr: "Market" },
  { id: 31, en: "Outdoor", tr: "Açık Hava / Dış Mekan" },
  { id: 32, en: "Indoor", tr: "Kapalı / İç Mekan" },
  { id: 33, en: "Shopping Centre", tr: "Alışveriş Merkezi" },
  { id: 34, en: "Department Store", tr: "Büyük Mağaza" },
  { id: 35, en: "Hypermarket", tr: "Hipermarket" },
  { id: 36, en: "Butcher's", tr: "Kasap" },
  { id: 37, en: "Chemist's", tr: "Eczane" },
  { id: 38, en: "Paper Shop / Newsagent", tr: "Gazete Bayii" },
  { id: 39, en: "Convenient", tr: "Uygun" },
  { id: 40, en: "Get", tr: "Edinmek / Almak" },
  { id: 41, en: "Do The Shopping", tr: "Alışveriş Yapmak" },
  { id: 42, en: "Queue", tr: "Sıra / Kuyruk" },
  { id: 43, en: "Check Out", tr: "Kasa" },
  { id: 44, en: "Choose", tr: "Seçmek" },
  { id: 45, en: "Prefer", tr: "Tercih Etmek" },
  { id: 46, en: "Fill", tr: "Doldurmak" },
  { id: 47, en: "Full", tr: "Dolu" },
  { id: 48, en: "Trolley", tr: "Alışveriş Arabası" },
  { id: 49, en: "Deliver", tr: "İletmek / Ulaştırmak" },
  { id: 50, en: "(on) The Top Floor", tr: "Üst Katta" },
  { id: 51, en: "(on) The Second Floor", tr: "İkinci Katta" },
  { id: 52, en: "(on) The First Floor", tr: "Birinci Katta" },
  { id: 53, en: "(on) The Ground Floor", tr: "Zemin Katta" },
  { id: 54, en: "Garden", tr: "Bahçe" },
  { id: 55, en: "Steps", tr: "Merdivenler / Basamaklar" },
  { id: 56, en: "(in) The Basement", tr: "Bodrumda" },
  { id: 57, en: "Rubbish", tr: "Çöp" },
  { id: 58, en: "Front Door", tr: "Sokak Kapısı / Ön Kapı" },
  { id: 59, en: "Stairs", tr: "Merdivenler" },
  { id: 60, en: "Lift", tr: "Asansör" },
  { id: 61, en: "Flat", tr: "Daire" },
  { id: 62, en: "Balcony", tr: "Balkon" },
  { id: 63, en: "Modern", tr: "Modern" },
  { id: 64, en: "Old", tr: "Eski" },
  { id: 65, en: "View", tr: "Görüntü / Manzara" },
  { id: 66, en: "Upstairs", tr: "Üst Kat" },
  { id: 67, en: "Downstairs", tr: "Alt Kat" },
  { id: 68, en: "Outside", tr: "Dışarısı" },
  { id: 69, en: "Inside", tr: "İçerisi" },
  { id: 70, en: "Garage", tr: "Garaj" },
  { id: 71, en: "Parking", tr: "Park Yeri" },
  { id: 72, en: "Living Room", tr: "Oturma Odası" },
  { id: 73, en: "Dining Room", tr: "Yemek Odası" },
  { id: 74, en: "Study Room", tr: "Çalışma Odası" },
  { id: 75, en: "Kitchen", tr: "Mutfak" },
  { id: 76, en: "Home", tr: "Ev" },
  { id: 77, en: "House", tr: "Bina" },
  { id: 78, en: "Shelf", tr: "Raf" },
  { id: 79, en: "Tap (turn the Tap on-off)", tr: "Musluk" },
  { id: 80, en: "Cup", tr: "Fincan" },
  { id: 81, en: "Microwave", tr: "Mikrodalga" },
  { id: 82, en: "Frying Pan", tr: "Kızartma Tavası" },
  { id: 83, en: "Freezer", tr: "Dondurucu" },
  { id: 84, en: "Sink", tr: "Lavabo" },
  { id: 85, en: "Saucer", tr: "Çay Tabağı / Fincan Tabağı" },
  { id: 86, en: "Hob", tr: "Set Üstü Ocak" },
  { id: 87, en: "Saucepan", tr: "Sos Tavası" },
  { id: 88, en: "(rubbish) Bin", tr: "Çöp Kovası" },
  { id: 89, en: "Full", tr: "Dolu" },
  { id: 90, en: "Empty", tr: "Boş" },
  { id: 91, en: "Oven", tr: "Fırın" },
  { id: 92, en: "Fridge", tr: "Buzdolabı" },
  { id: 93, en: "Washing Machine", tr: "Çamaşır Makinası" },
  { id: 94, en: "Cupboard", tr: "Dolap" },
  { id: 95, en: "Dishwasher", tr: "Bulaşık Makinası" },
  { id: 96, en: "Cooker", tr: "Ocak" },
  { id: 97, en: "Do The Shopping", tr: "Alışveriş Yapmak" },
  { id: 98, en: "Clean", tr: "Temizlemek" },
  { id: 99, en: "Take", tr: "Almak" },
  { id: 100, en: "Make", tr: "Yapmak" },
  { id: 101, en: "Do the Ironing", tr: "Ütü Yapmak" },
  { id: 102, en: "Do the Washing Up", tr: "Bulaşıkları Yıkamak" },
  { id: 103, en: "Housework", tr: "Ev İşi" },
  { id: 104, en: "Homework", tr: "Ev Ödevi" },
  { id: 105, en: "Bedroom", tr: "Yatak Odası" },
  { id: 106, en: "Single Bed", tr: "Tekli Yatak" },
  { id: 107, en: "Bedside Table", tr: "Komodin" },
  { id: 108, en: "Desk", tr: "Sıra / Masa" },
  { id: 109, en: "Chest of Drawers", tr: "Çekmeceler" },
  { id: 110, en: "Wardrobe", tr: "Gardırop" },
  { id: 111, en: "Bath", tr: "Banyo" },
  { id: 112, en: "Shower", tr: "Duş" },
  { id: 113, en: "Wash Basin", tr: "Lavabo" },
  { id: 114, en: "Mirror", tr: "Ayna" },
  { id: 115, en: "Blanket", tr: "Battaniye" },
  { id: 116, en: "Sheets", tr: "Çarşaflar" },
  { id: 117, en: "Towels", tr: "Havlular" },
  { id: 118, en: "Soap", tr: "Sabun" },
  { id: 119, en: "Have a Wash", tr: "Yıkanmak" },
  { id: 120, en: "Clean Your Teeth", tr: "Dişlerini Temizlemek" },
  { id: 121, en: "Wash Your Hair", tr: "Saçlarını Yıkamak" },
  { id: 122, en: "Have a Shave", tr: "Tıraş Olmak" },
  { id: 123, en: "Put On Make Up", tr: "Makyaj Yapmak" },
  { id: 124, en: "Take Off Make Up", tr: "Makyajı Çıkarmak / Silmek" },
  { id: 125, en: "Tissue", tr: "Mendil" },
  { id: 126, en: "Put On Perfume", tr: "Parfüm Sıkmak" },
  { id: 127, en: "Wear Perfume", tr: "Parfüm Sıkmak" },
  { id: 128, en: "A Razor", tr: "Jilet" },
  { id: 129, en: "Toothpaste", tr: "Diş Macunu" },
  { id: 130, en: "Toothbrush", tr: "Diş Fırçası" },
  { id: 131, en: "Window", tr: "Pencere" },
  { id: 132, en: "Light", tr: "Işık" },
  { id: 133, en: "Ceiling", tr: "Tavan" },
  { id: 134, en: "Wall", tr: "Duvar" },
  { id: 135, en: "Curtains", tr: "Perdeler" },
  { id: 136, en: "Cushion", tr: "Minder / Yastık" },
  { id: 137, en: "Lamp", tr: "Lamba" },
  { id: 138, en: "Armchair", tr: "Tekli Koltuk" },
  { id: 139, en: "Coffee Table", tr: "Orta Sehpa" },
  { id: 140, en: "Floor", tr: "Yer / Kat" },
  { id: 141, en: "Sofa", tr: "Çekyat" },
  { id: 142, en: "Rug", tr: "Kilim" },
  { id: 143, en: "Carpet", tr: "Halı" },
  { id: 144, en: "Chemistry", tr: "Kimya" },
  { id: 145, en: "Physics", tr: "Fizik" },
  { id: 146, en: "Biology", tr: "Biyoloji" },
  { id: 147, en: "Maths", tr: "Matematik" },
  { id: 148, en: "Geography", tr: "Coğrafya" },
  { id: 149, en: "History", tr: "Tarih" },
  { id: 150, en: "Literature", tr: "Edebiyat" },
  { id: 151, en: "Art", tr: "Resim / Sanat" },
  { id: 152, en: "Subjects", tr: "Konular / Dersler" },
  { id: 153, en: "Good at Something", tr: "Bir Şeyde İyi Olmak" },
  { id: 154, en: "Bad at Something", tr: "Bir Şeyde Kötü Olmak" },
  { id: 155, en: "Terrible At", tr: "Bir Şeyde Çok Kötü Olmak" },
  { id: 156, en: "Kindergarten", tr: "Anaokulu / Kreş" },
  { id: 157, en: "Primary School", tr: "İlkokul" },
  { id: 158, en: "Secondary School", tr: "Ortaokul" },
  { id: 159, en: "State School", tr: "Devlet Okulu" },
  { id: 160, en: "Private School", tr: "Özel Okul" },
  { id: 161, en: "Start at School", tr: "Okula Başlamak" },
  { id: 162, en: "Leave School", tr: "Okuldan Ayrılmak" },
  { id: 163, en: "Get a Job", tr: "İşe Girmek / İş Bulmak" },
  { id: 164, en: "Take Exam", tr: "Sınav Olmak" },
  { id: 165, en: "Pass an Exam", tr: "Bir Sınavı Geçmek" },
  { id: 166, en: "Fail an Exam", tr: "Bir Sınavdan Kalmak" },
  { id: 167, en: "Result", tr: "Sonuç" },
  { id: 168, en: "Grade", tr: "Not / Sınav Sonucu" },
  { id: 169, en: "Get a Grade", tr: "Sınav Sonucu Almak" },
  { id: 170, en: "Do Well", tr: "İyi Yapmak" },
  { id: 171, en: "Do Badly", tr: "Kötü Bir Şekilde Yapmak" },
  { id: 172, en: "Do a Degree", tr: "Derece Yapmak" },
  { id: 173, en: "Term", tr: "Dönem" },
  { id: 174, en: "Library", tr: "Kütüphane" },
  { id: 175, en: "Undergraduate", tr: "Lisans Öğrencisi" },
  { id: 176, en: "Write an Essay", tr: "Bir Deneme Yazısı Yazmak" },
  { id: 177, en: "Again", tr: "Yeniden" },
  { id: 178, en: "Psychology", tr: "Psikoloji" },
  { id: 179, en: "A Psychologist", tr: "Psikolog" },
  { id: 180, en: "Economics", tr: "Ekonomi" },
  { id: 181, en: "Economist", tr: "Ekonomist" },
  { id: 182, en: "Law", tr: "Hukuk" },
  { id: 183, en: "Lawyer", tr: "Avukat" },
  { id: 184, en: "Politics", tr: "Siyaset" },
  { id: 185, en: "A Politician", tr: "Siyasetçi" },
  { id: 186, en: "Engineering", tr: "Mühendislik" },
  { id: 187, en: "An Engineer", tr: "Mühendis" },
  { id: 188, en: "Architecture", tr: "Mimarlık" },
  { id: 189, en: "An Architect", tr: "Mimar" },
  { id: 190, en: "A Builder", tr: "İnşaatçı" },
  { id: 191, en: "A Teacher", tr: "Öğretmen" },
  { id: 192, en: "A Shop Assistant", tr: "Satıcı" },
  { id: 193, en: "A Nurse", tr: "Hemşire" },
  { id: 194, en: "A Secretary", tr: "Sekreter" },
  { id: 195, en: "A Hairdresser", tr: "Kuaför" },
  { id: 196, en: "A Chef", tr: "Şef" },
  { id: 197, en: "A Dentist", tr: "Dişçi" },
  { id: 198, en: "A Soldier", tr: "Asker" },
  { id: 199, en: "A Cleaner", tr: "Temizlikçi" },
  { id: 200, en: "A Vet", tr: "Veteriner" },
  { id: 201, en: "A Pilot", tr: "Pilot" },
  { id: 202, en: "A Lorry Driver", tr: "Kamyonet Sürücüsü" },
  { id: 203, en: "Self-Employed", tr: "Kendi İşinin Sahibi" },
  { id: 204, en: "Unemployed", tr: "İşsiz" },
  { id: 205, en: "Retired", tr: "Emekli" },
  { id: 206, en: "Housewife", tr: "Ev Hanımı" },
  { id: 207, en: "Boss", tr: "Patron" },
  { id: 208, en: "An Office", tr: "Ofis" },
  { id: 209, en: "A Factory", tr: "Fabrika" },
  { id: 210, en: "Company", tr: "Şirket" },
  { id: 211, en: "Full-Time", tr: "Tam Zamanlı" },
  { id: 212, en: "Part-Time", tr: "Yarı Zamanlı" },
  { id: 213, en: "Long Hours", tr: "Uzun Saatler" },
  { id: 214, en: "Earn", tr: "Kazanmak (Para)" },
  { id: 215, en: "Salary", tr: "Maaş" },
  { id: 216, en: "Wages", tr: "Günlük Ücret" },
  { id: 217, en: "Low", tr: "Düşük" },
  { id: 218, en: "High", tr: "Yüksek" },
  { id: 219, en: "Design Building", tr: "Bina Tasarlamak" },
  { id: 220, en: "Discuss Something", tr: "Bir Şeyi Tartışmak" },
  { id: 221, en: "To Go To Meeting", tr: "Bir Toplantıya Gitmek" },
  { id: 222, en: "Write a Report", tr: "Bir Rapor Yazmak" },
  { id: 223, en: "Organize Meeting", tr: "Toplantı Organize Etmek" },
  { id: 224, en: "Colleague", tr: "İş Arkadaşı / Meslektaş" },
  { id: 225, en: "Webcam", tr: "Video Kamera / İnternet Kamerası" },
  { id: 226, en: "Printer", tr: "Yazıcı" },
  { id: 227, en: "Laptop", tr: "Dizüstü Bilgisayar" },
  { id: 228, en: "Hard Drive", tr: "Sabit Disk" },
  { id: 229, en: "Monitor", tr: "Monitör" },
  { id: 230, en: "Disc", tr: "Disk" },
  { id: 231, en: "Mouse", tr: "Fare" },
  { id: 232, en: "Memory Stick", tr: "Taşınabilir Bellek" },
  { id: 233, en: "Screen", tr: "Ekran" },
  { id: 234, en: "Cut", tr: "Kesmek" },
  { id: 235, en: "Paste", tr: "Yapıştırmak" },
  { id: 236, en: "Save", tr: "Kaydetmek" },
  { id: 237, en: "Print", tr: "Yazdırmak" },
  { id: 238, en: "Copy", tr: "Kopyasını Almak / Kopyalamak" },
  { id: 239, en: "Check Your Email", tr: "E-Posta Kontrol Etmek" },
  { id: 240, en: "Get an Email", tr: "Bir E-Posta Almak" },
  { id: 241, en: "Reply To An Email", tr: "Bir E-Postaya Cevap Vermek" },
  { id: 242, en: "On The Internet", tr: "İnternette" },
  { id: 243, en: "Search", tr: "Araştırmak" },
  { id: 244, en: "Wonderful / Fantastic", tr: "Harika / Büyüleyici" },
  { id: 245, en: "Favourite", tr: "Favori" },
  { id: 246, en: "Enjoy Doing Something", tr: "Bir Şeyi Yapmaktan Keyif Almak" },
  { id: 247, en: "Boring", tr: "Sıkıcı" },
  { id: 248, en: "Be Keen On Something", tr: "Bir Şeye Çok İstekli Olmak" },
  { id: 249, en: "To Be Interested In", tr: "Bir Şeye İlgili Olmak" },
  { id: 250, en: "Prefer", tr: "Tercih Etmek" },
  { id: 251, en: "Camping", tr: "Kamp Yapma / Kamp" },
  { id: 252, en: "Travelling", tr: "Seyahat Etme / Seyahat" },
  { id: 253, en: "Collect Things", tr: "Bir Şeyler Toplamak" },
  { id: 254, en: "Skiing", tr: "Kayak Yapma / Kayak" },
  { id: 255, en: "Fishing", tr: "Balık Tutma" },
  { id: 256, en: "Spend Time", tr: "Zaman Geçirmek / Harcamak" },
  { id: 257, en: "Gym", tr: "Spor / Spor Salonu" },
  { id: 258, en: "Drawing", tr: "Çizim Yapma / Çizim" },
  { id: 259, en: "Painting", tr: "Resim Yapma / Resim / Tablo" },
  { id: 260, en: "Gardening", tr: "Bahçecilik" },
  { id: 261, en: "Repair Cars", tr: "Arabaları Tamir Etmek" },
  { id: 262, en: "Listen to Something", tr: "Bir Şeyi Dinlemek" },
  { id: 263, en: "Shooting", tr: "Atış Yapma / Atış" },
  { id: 264, en: "Singing", tr: "Şarkı Söyleme" },
  { id: 265, en: "Band", tr: "Müzik Grubu" },
  { id: 266, en: "Well-Known", tr: "İyi Bilinen" },
  { id: 267, en: "Lead Singer", tr: "Solist (Müzik Grubunun)" },
  { id: 268, en: "Concert", tr: "Konser" },
  { id: 269, en: "Conductor", tr: "Orkestra Şefi" },
  { id: 270, en: "Violinist", tr: "Kemancı" },
  { id: 271, en: "Violin", tr: "Keman" },
  { id: 272, en: "Composer", tr: "Bestekar" },
  { id: 273, en: "Perform", tr: "İcra Etmek" },
  { id: 274, en: "Thriller", tr: "Gerilim" },
  { id: 275, en: "Exciting", tr: "Heyecan Verici" },
  { id: 276, en: "Comedy", tr: "Komedi" },
  { id: 277, en: "Funny", tr: "Eğlenceli" },
  { id: 278, en: "Violent", tr: "Şiddetli / Şiddet İçerikli" },
  { id: 279, en: "Love Story", tr: "Aşk Hikayesi" },
  { id: 280, en: "Cinema", tr: "Sinema" },
  { id: 281, en: "Movie", tr: "Film" },
  { id: 282, en: "Review", tr: "İnceleme" },
  { id: 283, en: "Star", tr: "Yıldız" },
  { id: 284, en: "Actor", tr: "Aktör" },
  { id: 285, en: "See a Film At the Cinema", tr: "Sinemada Bir Film İzlemek" },
  { id: 286, en: "Media", tr: "Medya" },
  { id: 287, en: "Magazine", tr: "Dergi" },
  { id: 288, en: "Report", tr: "Rapor" },
  { id: 289, en: "Event", tr: "Olay" },
  { id: 290, en: "Die", tr: "Ölmek" },
  { id: 291, en: "War", tr: "Savaş" },
  { id: 292, en: "Peace", tr: "Barış / Huzur" },
  { id: 293, en: "Disaster", tr: "Felaket" },
  { id: 294, en: "Celebrity", tr: "Ünlü (Kişi)" },
  { id: 295, en: "Advert / Advertisement", tr: "İlan / Reklam" },
  { id: 296, en: "Newspaper / Paper", tr: "Gazete" },
  { id: 297, en: "Find Out", tr: "Bulmak" },
  { id: 298, en: "Happen", tr: "Olmak / Meydana Gelmek" },
  { id: 299, en: "Article", tr: "Makale" },
  { id: 300, en: "On TV", tr: "Televizyonda" },
  { id: 301, en: "On the Radio", tr: "Radyoda" },
  { id: 302, en: "Nothing Much / Nothing Important", tr: "Önemli Bir Şey Değil" },
  { id: 303, en: "Weather Forecast", tr: "Hava Durumu / Tahmini" },
  { id: 304, en: "Believe", tr: "İnanmak" },
  { id: 305, en: "To Go Abroad", tr: "Yurtdışına Gitmek" },
  { id: 306, en: "To Book a Flight", tr: "Bir Uçuş Rezervasyonu Yapmak" },
  { id: 307, en: "Find Your Passport", tr: "Pasaportunu Bulmak" },
  { id: 308, en: "To Get a Visa", tr: "Vize Almak" },
  { id: 309, en: "To Get Travel Insurance", tr: "Seyahat Sigortası Almak" },
  { id: 310, en: "To Get Foreign Currency", tr: "Yabancı Ülke Parası Almak" },
  { id: 311, en: "To Pack Your Suitcase", tr: "Valizini Toplamak" },
  { id: 312, en: "To Hire a Car", tr: "Araba Kiralamak" },
  { id: 313, en: "To Arrange Something", tr: "Bir Şey Ayarlamak" },
  { id: 314, en: "On Holiday", tr: "Tatilde" },
  { id: 315, en: "Currency", tr: "Döviz" },
  { id: 316, en: "To Stay in a Hotel", tr: "Bir Otelde Kalmak" },
  { id: 317, en: "Facilities", tr: "Özellikler" },
  { id: 318, en: "Air Conditioning", tr: "Klima" },
  { id: 319, en: "Central Heating", tr: "Merkezi Isıtma" },
  { id: 320, en: "Staff", tr: "Personel / Kadro" },
  { id: 321, en: "Helpful", tr: "Yardımcı / Yardımsever" },
  { id: 322, en: "Tourist", tr: "Turist" },
  { id: 323, en: "Delicious", tr: "Lezzetli" },
  { id: 324, en: "Recommend", tr: "Önermek" },
  { id: 325, en: "To Book A Room", tr: "Bir Oda Rezervasyonu Yapmak" },
  { id: 326, en: "Included", tr: "İçeren" },
  { id: 327, en: "Never Mind", tr: "Dert Etme / Boşver" },
  { id: 328, en: "Details", tr: "Detaylar" },
  { id: 329, en: "Double Room", tr: "Çift Kişilik Oda" },
  { id: 330, en: "Single Room", tr: "Tek Kişilik Oda" },
  { id: 331, en: "Twin Room", tr: "Çift Yataklı Oda" },
  { id: 332, en: "That's a Shame", tr: "Bu Bir Utanç" },
  { id: 333, en: "What a Shame", tr: "Ne Utanç Verici" },
  { id: 334, en: "Passengers", tr: "Yolcular" },
  { id: 335, en: "Airport", tr: "Havaalanı" },
  { id: 336, en: "Luggage / Suitcase / Bag", tr: "Bagaj / Valiz / Çanta" },
  { id: 337, en: "Ticket", tr: "Bilet" },
  { id: 338, en: "Hand Luggage", tr: "El Bagajı" },
  { id: 339, en: "Window Seat", tr: "Pencere Koltuğu" },
  { id: 340, en: "Aisle", tr: "Koridor" },
  { id: 341, en: "Have a Good Flight", tr: "İyi Uçuşlar" },
  { id: 342, en: "Departed", tr: "Ayrılmış" },
  { id: 343, en: "Departure", tr: "Havalanma / Kalkış" },
  { id: 344, en: "Gate", tr: "Kapı" },
  { id: 345, en: "Delay", tr: "Gecikme" },
  { id: 346, en: "Fasten Seat Belt", tr: "Emniyet Kemeri Takmak" },
  { id: 347, en: "Plane Takes Off", tr: "Uçak Kalkar" },
  { id: 348, en: "Plane Lands", tr: "Uçak İner" },
  { id: 349, en: "Baggage Reclaim", tr: "Bagaj Teslim" },
  { id: 350, en: "To Go Through Customs", tr: "Gümrükten Geçmek" },
  { id: 351, en: "Resort", tr: "Tatil Yeri" },
  { id: 352, en: "Fly", tr: "Uçuş Yapmak" },
  { id: 353, en: "Rent an Apartment", tr: "Apartman Dairesi Kiralamak" },
  { id: 354, en: "Sunbathe", tr: "Güneşlenmek" },
  { id: 355, en: "Relax", tr: "Rahatlamak" },
  { id: 356, en: "An Hour or So", tr: "Bir Saate Kadar" },
  { id: 357, en: "To Go For a Walk", tr: "Yürüyüşe Çıkmak" },
  { id: 358, en: "Perfect", tr: "Mükemmel" },
  { id: 359, en: "Map", tr: "Harita" },
  { id: 360, en: "Guide", tr: "Rehber" },
  { id: 361, en: "Guide Book", tr: "Rehber Kitap" },
  { id: 362, en: "To Go Sightseeing", tr: "Geziye Çıkmak / Bölge Turuna Çıkmak" },
  { id: 363, en: "Art Gallery", tr: "Sanat Galerisi" },
  { id: 364, en: "To Visit Museum", tr: "Müze Ziyaret Etmek" },
  { id: 365, en: "To Look Around", tr: "Bakınmak / Etrafı Seyretmek" },
  { id: 366, en: "To Get Lost", tr: "Kaybolmak" },
  { id: 367, en: "To Take Photos", tr: "Fotoğraf Çekmek" },
  { id: 368, en: "Cash Machine", tr: "Para Çekme Makinesi" },
  { id: 369, en: "Change Dollars into Euro", tr: "Doları Avroya Çevirmek" },
  { id: 370, en: "Exchange Rate", tr: "Döviz Kuru" },
  { id: 371, en: "Commission", tr: "Komisyon" },
  { id: 372, en: "To Charge Someone", tr: "Birini Suçlamak" },
  { id: 373, en: "Envelope", tr: "Zarf" },
  { id: 374, en: "Put a Stamp", tr: "Posta Pulu Koymak" },
  { id: 375, en: "Postman", tr: "Postacı (Erkek)" },
  { id: 376, en: "Postwoman", tr: "Postacı (Kadın)" },
  { id: 377, en: "A Parcel", tr: "Posta / Parsel / Koli" },
  { id: 378, en: "Have a Nice Day", tr: "İyi Günler" },
  { id: 379, en: "Have a Good Day", tr: "İyi Günler" },
  { id: 380, en: "Well Done", tr: "Aferin" },
  { id: 381, en: "Congratulations", tr: "Tebrikler" },
  { id: 382, en: "Good Luck", tr: "İyi Şanslar" },
  { id: 383, en: "Cheers", tr: "Şerefe" },
  { id: 384, en: "To Go Out For", tr: "Dışarı Çıkmak" },
  { id: 385, en: "Come Around For (a Drink)", tr: "İçmek İçin Dışarıda Buluşmak" },
  { id: 386, en: "Invite", tr: "Davet Etmek" },
  { id: 387, en: "Party", tr: "Parti" },
  { id: 388, en: "Great", tr: "Harika" },
  { id: 389, en: "I'd Love To", tr: "Çok İsterim" },
  { id: 390, en: "That Sounds Lovely", tr: "Kulağa Hoş Geliyor" },
  { id: 391, en: "I'm Afraid I Can't", tr: "Korkarım Yapamam" },
  { id: 392, en: "Suggest", tr: "Önermek" },
  { id: 393, en: "Offer", tr: "Ismarlamak" },
  { id: 394, en: "Accept", tr: "Kabul Etmek" },
  { id: 395, en: "Refuse", tr: "Geri Çevirmek" },
  { id: 396, en: "Let Me Pay", tr: "Bırak Ben Ödeyeyim" },
  { id: 397, en: "Let Me Give You a Lift", tr: "Ben Seni Bırakayım" },
  { id: 398, en: "Apologize To Something", tr: "Bir Şey İçin Özür Dilemek" },
  { id: 399, en: "Rude", tr: "Kaba" },
  { id: 400, en: "Lose", tr: "Kaybetmek" },
  { id: 401, en: "Excellent", tr: "Harika" },
  { id: 402, en: "Think", tr: "Düşünmek" },
  { id: 403, en: "Thought", tr: "Düşünce" },
  { id: 404, en: "Agree With Someone", tr: "Biriyle Aynı Fikirde Olmak" },
  { id: 405, en: "Personally", tr: "Kişisel Olarak" },
  { id: 406, en: "A Waste of Money / Time", tr: "Para / Zaman Kaybı / İsrafı" },
  { id: 407, en: "Take a Message", tr: "Mesaj / Not Almak" },
  { id: 408, en: "Leave a Message", tr: "Mesaj Bırakmak" },
  { id: 409, en: "Line is Busy / Engaged", tr: "Hat Meşgul" },
  { id: 410, en: "Wrong Number", tr: "Yanlış Numara" }
];
