const WORDS_A2 = [
  { id: 1, en: "Sky", tr: "Gökyüzü" },
  { id: 2, en: "Wood", tr: "Ağaçlık" },
  { id: 3, en: "Hill", tr: "Tepe" },
  { id: 4, en: "Farmer", tr: "Çiftçi" },
  { id: 5, en: "Valley", tr: "Vadi" },
  { id: 6, en: "Tree", tr: "Ağaç" },
  { id: 7, en: "Field", tr: "Alan / Tarla" },
  { id: 8, en: "Farm", tr: "Çiftlik" },
  { id: 9, en: "Lake", tr: "Göl" },
  { id: 10, en: "Horse", tr: "At" },
  { id: 11, en: "Boat", tr: "Kayık" },
  { id: 12, en: "Grass", tr: "Çimen" },
  { id: 13, en: "Dog", tr: "Köpek" },
  { id: 14, en: "Path", tr: "Patika / Keçi Yolu" },
  { id: 15, en: "Grow", tr: "Büyü(t)mek / Yetiş(tir)mek" },
  { id: 16, en: "Own", tr: "Sahip Olmak" },
  { id: 17, en: "Crop", tr: "Mahsul" },
  { id: 18, en: "Area", tr: "Alan / Bölge" },
  { id: 19, en: "Countryside", tr: "Kırsal Bölge" },
  { id: 20, en: "Bird", tr: "Kuş" },
  { id: 21, en: "Wonderful", tr: "Harika" },
  { id: 22, en: "Fresh Food", tr: "Taze Yiyecek" },
  { id: 23, en: "Healthy", tr: "Sağlıklı" },
  { id: 24, en: "Public Transport", tr: "Toplu Taşıma" },
  { id: 25, en: "Terrible", tr: "Korkunç" },
  { id: 26, en: "Ride a Bike", tr: "Bisiklete Binmek" },
  { id: 27, en: "Alone", tr: "Yalnız" },
  { id: 28, en: "Lonely", tr: "Yalnız Bir Şekilde" },
  { id: 29, en: "Look After", tr: "İlgilenmek" },
  { id: 30, en: "Market", tr: "Market" },
  { id: 31, en: "Outdoor", tr: "Açık Hava / Dış Mekan" },
  { id: 32, en: "Indoor", tr: "Kapalı / İç Mekan" },
  { id: 33, en: "Shopping Centre", tr: "Alışveriş Merkezi" },
  { id: 34, en: "Department Store", tr: "Büyük Mağaza" },
  { id: 35, en: "Hypermarket", tr: "Hipermarket" },
  { id: 36, en: "Butcher's", tr: "Kasap" },
  { id: 37, en: "Chemist's", tr: "Eczane" },
  { id: 38, en: "Paper Shop / Newsagent", tr: "Gazete Bayii" },
  { id: 39, en: "Convenient", tr: "Uygun" },
  { id: 40, en: "Get", tr: "Edinmek / Almak" },
  { id: 41, en: "Do The Shopping", tr: "Alışveriş Yapmak" },
  { id: 42, en: "Queue", tr: "Sıra / Kuyruk" },
  { id: 43, en: "Check Out", tr: "Kasa" },
  { id: 44, en: "Choose", tr: "Seçmek" },
  { id: 45, en: "Prefer", tr: "Tercih Etmek" },
  { id: 46, en: "Fill", tr: "Doldurmak" },
  { id: 47, en: "Full", tr: "Dolu" },
  { id: 48, en: "Trolley", tr: "Alışveriş Arabası" },
  { id: 49, en: "Deliver", tr: "İletmek / Ulaştırmak" },
  { id: 50, en: "(on) The Top Floor", tr: "Üst Katta" },
  { id: 51, en: "(on) The Second Floor", tr: "İkinci Katta" },
  { id: 52, en: "(on) The First Floor", tr: "Birinci Katta" },
  { id: 53, en: "(on) The Ground Floor", tr: "Zemin Katta" },
  { id: 54, en: "Garden", tr: "Bahçe" },
  { id: 55, en: "Steps", tr: "Merdivenler / Basamaklar" },
  { id: 56, en: "(in) The Basement", tr: "Bodrumda" },
  { id: 57, en: "Rubbish", tr: "Çöp" },
  { id: 58, en: "Front Door", tr: "Sokak Kapısı / Ön Kapı" },
  { id: 59, en: "Stairs", tr: "Merdivenler" },
  { id: 60, en: "Lift", tr: "Asansör" },
  { id: 61, en: "Flat", tr: "Daire" },
  { id: 62, en: "Balcony", tr: "Balkon" },
  { id: 63, en: "Modern", tr: "Modern" },
  { id: 64, en: "Old", tr: "Eski" },
  { id: 65, en: "View", tr: "Görüntü / Manzara" },
  { id: 66, en: "Upstairs", tr: "Üst Kat" },
  { id: 67, en: "Downstairs", tr: "Alt Kat" },
  { id: 68, en: "Outside", tr: "Dışarısı" },
  { id: 69, en: "Inside", tr: "İçerisi" },
  { id: 70, en: "Garage", tr: "Garaj" },
  { id: 71, en: "Parking", tr: "Park Yeri" },
  { id: 72, en: "Living Room", tr: "Oturma Odası" },
  { id: 73, en: "Dining Room", tr: "Yemek Odası" },
  { id: 74, en: "Study Room", tr: "Çalışma Odası" },
  { id: 75, en: "Kitchen", tr: "Mutfak" },
  { id: 76, en: "Home", tr: "Ev" },
  { id: 77, en: "House", tr: "Bina" },
  { id: 78, en: "Shelf", tr: "Raf" },
  { id: 79, en: "Tap (turn the Tap on-off)", tr: "Musluk" },
  { id: 80, en: "Cup", tr: "Fincan" },
  { id: 81, en: "Microwave", tr: "Mikrodalga" },
  { id: 82, en: "Frying Pan", tr: "Kızartma Tavası" },
  { id: 83, en: "Freezer", tr: "Dondurucu" },
  { id: 84, en: "Sink", tr: "Lavabo" },
  { id: 85, en: "Saucer", tr: "Çay Tabağı / Fincan Tabağı" },
  { id: 86, en: "Hob", tr: "Set Üstü Ocak" },
  { id: 87, en: "Saucepan", tr: "Sos Tavası" },
  { id: 88, en: "(rubbish) Bin", tr: "Çöp Kovası" },
  { id: 89, en: "Full", tr: "Dolu" },
  { id: 90, en: "Empty", tr: "Boş" },
  { id: 91, en: "Oven", tr: "Fırın" },
  { id: 92, en: "Fridge", tr: "Buzdolabı" },
  { id: 93, en: "Washing Machine", tr: "Çamaşır Makinası" },
  { id: 94, en: "Cupboard", tr: "Dolap" },
  { id: 95, en: "Dishwasher", tr: "Bulaşık Makinası" },
  { id: 96, en: "Cooker", tr: "Ocak" },
  { id: 97, en: "Do The Shopping", tr: "Alışveriş Yapmak" },
  { id: 98, en: "Clean", tr: "Temizlemek" },
  { id: 99, en: "Take", tr: "Almak" },
  { id: 100, en: "Make", tr: "Yapmak" },
  { id: 101, en: "Do the Ironing", tr: "Ütü Yapmak" },
  { id: 102, en: "Do the Washing Up", tr: "Bulaşıkları Yıkamak" },
  { id: 103, en: "Housework", tr: "Ev İşi" },
  { id: 104, en: "Homework", tr: "Ev Ödevi" },
  { id: 105, en: "Bedroom", tr: "Yatak Odası" },
  { id: 106, en: "Single Bed", tr: "Tekli Yatak" },
  { id: 107, en: "Bedside Table", tr: "Komodin" },
  { id: 108, en: "Desk", tr: "Sıra / Masa" },
  { id: 109, en: "Chest of Drawers", tr: "Çekmeceler" },
  { id: 110, en: "Wardrobe", tr: "Gardırop" },
  { id: 111, en: "Bath", tr: "Banyo" },
  { id: 112, en: "Shower", tr: "Duş" },
  { id: 113, en: "Wash Basin", tr: "Lavabo" },
  { id: 114, en: "Mirror", tr: "Ayna" },
  { id: 115, en: "Blanket", tr: "Battaniye" },
  { id: 116, en: "Sheets", tr: "Çarşaflar" },
  { id: 117, en: "Towels", tr: "Havlular" },
  { id: 118, en: "Soap", tr: "Sabun" },
  { id: 119, en: "Have a Wash", tr: "Yıkanmak" },
  { id: 120, en: "Clean Your Teeth", tr: "Dişlerini Temizlemek" },
  { id: 121, en: "Wash Your Hair", tr: "Saçlarını Yıkamak" },
  { id: 122, en: "Have a Shave", tr: "Tıraş Olmak" },
  { id: 123, en: "Put On Make Up", tr: "Makyaj Yapmak" },
  { id: 124, en: "Take Off Make Up", tr: "Makyajı Çıkarmak / Silmek" },
  { id: 125, en: "Tissue", tr: "Mendil" },
  { id: 126, en: "Put On Perfume", tr: "Parfüm Sıkmak" },
  { id: 127, en: "Wear Perfume", tr: "Parfüm Sıkmak" },
  { id: 128, en: "A Razor", tr: "Jilet" },
  { id: 129, en: "Toothpaste", tr: "Diş Macunu" },
  { id: 130, en: "Toothbrush", tr: "Diş Fırçası" },
  { id: 131, en: "Window", tr: "Pencere" },
  { id: 132, en: "Light", tr: "Işık" },
  { id: 133, en: "Ceiling", tr: "Tavan" },
  { id: 134, en: "Wall", tr: "Duvar" },
  { id: 135, en: "Curtains", tr: "Perdeler" },
  { id: 136, en: "Cushion", tr: "Minder / Yastık" },
  { id: 137, en: "Lamp", tr: "Lamba" },
  { id: 138, en: "Armchair", tr: "Tekli Koltuk" },
  { id: 139, en: "Coffee Table", tr: "Orta Sehpa" },
  { id: 140, en: "Floor", tr: "Yer / Kat" },
  { id: 141, en: "Sofa", tr: "Çekyat" },
  { id: 142, en: "Rug", tr: "Kilim" },
  { id: 143, en: "Carpet", tr: "Halı" },
  { id: 144, en: "Chemistry", tr: "Kimya" },
  { id: 145, en: "Physics", tr: "Fizik" },
  { id: 146, en: "Biology", tr: "Biyoloji" },
  { id: 147, en: "Maths", tr: "Matematik" },
  { id: 148, en: "Geography", tr: "Coğrafya" },
  { id: 149, en: "History", tr: "Tarih" },
  { id: 150, en: "Literature", tr: "Edebiyat" },
  { id: 151, en: "Art", tr: "Resim / Sanat" },
  { id: 152, en: "Subjects", tr: "Konular / Dersler" },
  { id: 153, en: "Good at Something", tr: "Bir Şeyde İyi Olmak" },
  { id: 154, en: "Bad at Something", tr: "Bir Şeyde Kötü Olmak" },
  { id: 155, en: "Terrible At", tr: "Bir Şeyde Çok Kötü Olmak" },
  { id: 156, en: "Kindergarten", tr: "Anaokulu / Kreş" },
  { id: 157, en: "Primary School", tr: "İlkokul" },
  { id: 158, en: "Secondary School", tr: "Ortaokul" },
  { id: 159, en: "State School", tr: "Devlet Okulu" },
  { id: 160, en: "Private School", tr: "Özel Okul" },
  { id: 161, en: "Start at School", tr: "Okula Başlamak" },
  { id: 162, en: "Leave School", tr: "Okuldan Ayrılmak" },
  { id: 163, en: "Get a Job", tr: "İşe Girmek / İş Bulmak" },
  { id: 164, en: "Take Exam", tr: "Sınav Olmak" },
  { id: 165, en: "Pass an Exam", tr: "Bir Sınavı Geçmek" },
  { id: 166, en: "Fail an Exam", tr: "Bir Sınavdan Kalmak" },
  { id: 167, en: "Result", tr: "Sonuç" },
  { id: 168, en: "Grade", tr: "Not / Sınav Sonucu" },
  { id: 169, en: "Get a Grade", tr: "Sınav Sonucu Almak" },
  { id: 170, en: "Do Well", tr: "İyi Yapmak" },
  { id: 171, en: "Do Badly", tr: "Kötü Bir Şekilde Yapmak" },
  { id: 172, en: "Do a Degree", tr: "Derece Yapmak" },
  { id: 173, en: "Term", tr: "Dönem" },
  { id: 174, en: "Library", tr: "Kütüphane" },
  { id: 175, en: "Undergraduate", tr: "Lisans Öğrencisi" },
  { id: 176, en: "Write an Essay", tr: "Bir Deneme Yazısı Yazmak" },
  { id: 177, en: "Again", tr: "Yeniden" },
  { id: 178, en: "Psychology", tr: "Psikoloji" },
  { id: 179, en: "A Psychologist", tr: "Psikolog" },
  { id: 180, en: "Economics", tr: "Ekonomi" },
  { id: 181, en: "Economist", tr: "Ekonomist" },
  { id: 182, en: "Law", tr: "Hukuk" },
  { id: 183, en: "Lawyer", tr: "Avukat" },
  { id: 184, en: "Politics", tr: "Siyaset" },
  { id: 185, en: "A Politician", tr: "Siyasetçi" },
  { id: 186, en: "Engineering", tr: "Mühendislik" },
  { id: 187, en: "An Engineer", tr: "Mühendis" },
  { id: 188, en: "Architecture", tr: "Mimarlık" },
  { id: 189, en: "An Architect", tr: "Mimar" },
  { id: 190, en: "A Builder", tr: "İnşaatçı" },
  { id: 191, en: "A Teacher", tr: "Öğretmen" },
  { id: 192, en: "A Shop Assistant", tr: "Satıcı" },
  { id: 193, en: "A Nurse", tr: "Hemşire" },
  { id: 194, en: "A Secretary", tr: "Sekreter" },
  { id: 195, en: "A Hairdresser", tr: "Kuaför" },
  { id: 196, en: "A Chef", tr: "Şef" },
  { id: 197, en: "A Dentist", tr: "Dişçi" },
  { id: 198, en: "A Soldier", tr: "Asker" },
  { id: 199, en: "A Cleaner", tr: "Temizlikçi" },
  { id: 200, en: "A Vet", tr: "Veteriner" },
  { id: 201, en: "A Pilot", tr: "Pilot" },
  { id: 202, en: "A Lorry Driver", tr: "Kamyonet Sürücüsü" },
  { id: 203, en: "Self-Employed", tr: "Kendi İşinin Sahibi" },
  { id: 204, en: "Unemployed", tr: "İşsiz" },
  { id: 205, en: "Retired", tr: "Emekli" },
  { id: 206, en: "Housewife", tr: "Ev Hanımı" },
  { id: 207, en: "Boss", tr: "Patron" },
  { id: 208, en: "An Office", tr: "Ofis" },
  { id: 209, en: "A Factory", tr: "Fabrika" },
  { id: 210, en: "Company", tr: "Şirket" },
  { id: 211, en: "Full-Time", tr: "Tam Zamanlı" },
  { id: 212, en: "Part-Time", tr: "Yarı Zamanlı" },
  { id: 213, en: "Long Hours", tr: "Uzun Saatler" },
  { id: 214, en: "Earn", tr: "Kazanmak (Para)" },
  { id: 215, en: "Salary", tr: "Maaş" },
  { id: 216, en: "Wages", tr: "Günlük Ücret" },
  { id: 217, en: "Low", tr: "Düşük" },
  { id: 218, en: "High", tr: "Yüksek" },
  { id: 219, en: "Design Building", tr: "Bina Tasarlamak" },
  { id: 220, en: "Discuss Something", tr: "Bir Şeyi Tartışmak" },
  { id: 221, en: "To Go To Meeting", tr: "Bir Toplantıya Gitmek" },
  { id: 222, en: "Write a Report", tr: "Bir Rapor Yazmak" },
  { id: 223, en: "Organize Meeting", tr: "Toplantı Organize Etmek" },
  { id: 224, en: "Colleague", tr: "İş Arkadaşı / Meslektaş" },
  { id: 225, en: "Webcam", tr: "Video Kamera / İnternet Kamerası" },
  { id: 226, en: "Printer", tr: "Yazıcı" },
  { id: 227, en: "Laptop", tr: "Dizüstü Bilgisayar" },
  { id: 228, en: "Hard Drive", tr: "Sabit Disk" },
  { id: 229, en: "Monitor", tr: "Monitör" },
  { id: 230, en: "Disc", tr: "Disk" },
  { id: 231, en: "Mouse", tr: "Fare" },
  { id: 232, en: "Memory Stick", tr: "Taşınabilir Bellek" },
  { id: 233, en: "Screen", tr: "Ekran" },
  { id: 234, en: "Cut", tr: "Kesmek" },
  { id: 235, en: "Paste", tr: "Yapıştırmak" },
  { id: 236, en: "Save", tr: "Kaydetmek" },
  { id: 237, en: "Print", tr: "Yazdırmak" },
  { id: 238, en: "Copy", tr: "Kopyasını Almak / Kopyalamak" },
  { id: 239, en: "Check Your Email", tr: "E-Posta Kontrol Etmek" },
  { id: 240, en: "Get an Email", tr: "Bir E-Posta Almak" },
  { id: 241, en: "Reply To An Email", tr: "Bir E-Postaya Cevap Vermek" },
  { id: 242, en: "On The Internet", tr: "İnternette" },
  { id: 243, en: "Search", tr: "Araştırmak" },
  { id: 244, en: "Wonderful / Fantastic", tr: "Harika / Büyüleyici" },
  { id: 245, en: "Favourite", tr: "Favori" },
  { id: 246, en: "Enjoy Doing Something", tr: "Bir Şeyi Yapmaktan Keyif Almak" },
  { id: 247, en: "Boring", tr: "Sıkıcı" },
  { id: 248, en: "Be Keen On Something", tr: "Bir Şeye Çok İstekli Olmak" },
  { id: 249, en: "To Be Interested In", tr: "Bir Şeye İlgili Olmak" },
  { id: 250, en: "Prefer", tr: "Tercih Etmek" },
  { id: 251, en: "Camping", tr: "Kamp Yapma / Kamp" },
  { id: 252, en: "Travelling", tr: "Seyahat Etme / Seyahat" },
  { id: 253, en: "Collect Things", tr: "Bir Şeyler Toplamak" },
  { id: 254, en: "Skiing", tr: "Kayak Yapma / Kayak" },
  { id: 255, en: "Fishing", tr: "Balık Tutma" },
  { id: 256, en: "Spend Time", tr: "Zaman Geçirmek / Harcamak" },
  { id: 257, en: "Gym", tr: "Spor / Spor Salonu" },
  { id: 258, en: "Drawing", tr: "Çizim Yapma / Çizim" },
  { id: 259, en: "Painting", tr: "Resim Yapma / Resim / Tablo" },
  { id: 260, en: "Gardening", tr: "Bahçecilik" },
  { id: 261, en: "Repair Cars", tr: "Arabaları Tamir Etmek" },
  { id: 262, en: "Listen to Something", tr: "Bir Şeyi Dinlemek" },
  { id: 263, en: "Shooting", tr: "Atış Yapma / Atış" },
  { id: 264, en: "Singing", tr: "Şarkı Söyleme" },
  { id: 265, en: "Band", tr: "Müzik Grubu" },
  { id: 266, en: "Well-Known", tr: "İyi Bilinen" },
  { id: 267, en: "Lead Singer", tr: "Solist (Müzik Grubunun)" },
  { id: 268, en: "Concert", tr: "Konser" },
  { id: 269, en: "Conductor", tr: "Orkestra Şefi" },
  { id: 270, en: "Violinist", tr: "Kemancı" },
  { id: 271, en: "Violin", tr: "Keman" },
  { id: 272, en: "Composer", tr: "Bestekar" },
  { id: 273, en: "Perform", tr: "İcra Etmek" },
  { id: 274, en: "Thriller", tr: "Gerilim" },
  { id: 275, en: "Exciting", tr: "Heyecan Verici" },
  { id: 276, en: "Comedy", tr: "Komedi" },
  { id: 277, en: "Funny", tr: "Eğlenceli" },
  { id: 278, en: "Violent", tr: "Şiddetli / Şiddet İçerikli" },
  { id: 279, en: "Love Story", tr: "Aşk Hikayesi" },
  { id: 280, en: "Cinema", tr: "Sinema" },
  { id: 281, en: "Movie", tr: "Film" },
  { id: 282, en: "Review", tr: "İnceleme" },
  { id: 283, en: "Star", tr: "Yıldız" },
  { id: 284, en: "Actor", tr: "Aktör" },
  { id: 285, en: "See a Film At the Cinema", tr: "Sinemada Bir Film İzlemek" },
  { id: 286, en: "Media", tr: "Medya" },
  { id: 287, en: "Magazine", tr: "Dergi" },
  { id: 288, en: "Report", tr: "Rapor" },
  { id: 289, en: "Event", tr: "Olay" },
  { id: 290, en: "Die", tr: "Ölmek" },
  { id: 291, en: "War", tr: "Savaş" },
  { id: 292, en: "Peace", tr: "Barış / Huzur" },
  { id: 293, en: "Disaster", tr: "Felaket" },
  { id: 294, en: "Celebrity", tr: "Ünlü (Kişi)" },
  { id: 295, en: "Advert / Advertisement", tr: "İlan / Reklam" },
  { id: 296, en: "Newspaper / Paper", tr: "Gazete" },
  { id: 297, en: "Find Out", tr: "Bulmak" },
  { id: 298, en: "Happen", tr: "Olmak / Meydana Gelmek" },
  { id: 299, en: "Article", tr: "Makale" },
  { id: 300, en: "On TV", tr: "Televizyonda" },
  { id: 301, en: "On the Radio", tr: "Radyoda" },
  { id: 302, en: "Nothing Much / Nothing Important", tr: "Önemli Bir Şey Değil" },
  { id: 303, en: "Weather Forecast", tr: "Hava Durumu / Tahmini" },
  { id: 304, en: "Believe", tr: "İnanmak" },
  { id: 305, en: "To Go Abroad", tr: "Yurtdışına Gitmek" },
  { id: 306, en: "To Book a Flight", tr: "Bir Uçuş Rezervasyonu Yapmak" },
  { id: 307, en: "Find Your Passport", tr: "Pasaportunu Bulmak" },
  { id: 308, en: "To Get a Visa", tr: "Vize Almak" },
  { id: 309, en: "To Get Travel Insurance", tr: "Seyahat Sigortası Almak" },
  { id: 310, en: "To Get Foreign Currency", tr: "Yabancı Ülke Parası Almak" },
  { id: 311, en: "To Pack Your Suitcase", tr: "Valizini Toplamak" },
  { id: 312, en: "To Hire a Car", tr: "Araba Kiralamak" },
  { id: 313, en: "To Arrange Something", tr: "Bir Şey Ayarlamak" },
  { id: 314, en: "On Holiday", tr: "Tatilde" },
  { id: 315, en: "Currency", tr: "Döviz" },
  { id: 316, en: "To Stay in a Hotel", tr: "Bir Otelde Kalmak" },
  { id: 317, en: "Facilities", tr: "Özellikler" },
  { id: 318, en: "Air Conditioning", tr: "Klima" },
  { id: 319, en: "Central Heating", tr: "Merkezi Isıtma" },
  { id: 320, en: "Staff", tr: "Personel / Kadro" },
  { id: 321, en: "Helpful", tr: "Yardımcı / Yardımsever" },
  { id: 322, en: "Tourist", tr: "Turist" },
  { id: 323, en: "Delicious", tr: "Lezzetli" },
  { id: 324, en: "Recommend", tr: "Önermek" },
  { id: 325, en: "To Book A Room", tr: "Bir Oda Rezervasyonu Yapmak" },
  { id: 326, en: "Included", tr: "İçeren" },
  { id: 327, en: "Never Mind", tr: "Dert Etme / Boşver" },
  { id: 328, en: "Details", tr: "Detaylar" },
  { id: 329, en: "Double Room", tr: "Çift Kişilik Oda" },
  { id: 330, en: "Single Room", tr: "Tek Kişilik Oda" },
  { id: 331, en: "Twin Room", tr: "Çift Yataklı Oda" },
  { id: 332, en: "That's a Shame", tr: "Bu Bir Utanç" },
  { id: 333, en: "What a Shame", tr: "Ne Utanç Verici" },
  { id: 334, en: "Passengers", tr: "Yolcular" },
  { id: 335, en: "Airport", tr: "Havaalanı" },
  { id: 336, en: "Luggage / Suitcase / Bag", tr: "Bagaj / Valiz / Çanta" },
  { id: 337, en: "Ticket", tr: "Bilet" },
  { id: 338, en: "Hand Luggage", tr: "El Bagajı" },
  { id: 339, en: "Window Seat", tr: "Pencere Koltuğu" },
  { id: 340, en: "Aisle", tr: "Koridor" },
  { id: 341, en: "Have a Good Flight", tr: "İyi Uçuşlar" },
  { id: 342, en: "Departed", tr: "Ayrılmış" },
  { id: 343, en: "Departure", tr: "Havalanma / Kalkış" },
  { id: 344, en: "Gate", tr: "Kapı" },
  { id: 345, en: "Delay", tr: "Gecikme" },
  { id: 346, en: "Fasten Seat Belt", tr: "Emniyet Kemeri Takmak" },
  { id: 347, en: "Plane Takes Off", tr: "Uçak Kalkar" },
  { id: 348, en: "Plane Lands", tr: "Uçak İner" },
  { id: 349, en: "Baggage Reclaim", tr: "Bagaj Teslim" },
  { id: 350, en: "To Go Through Customs", tr: "Gümrükten Geçmek" },
  { id: 351, en: "Resort", tr: "Tatil Yeri" },
  { id: 352, en: "Fly", tr: "Uçuş Yapmak" },
  { id: 353, en: "Rent an Apartment", tr: "Apartman Dairesi Kiralamak" },
  { id: 354, en: "Sunbathe", tr: "Güneşlenmek" },
  { id: 355, en: "Relax", tr: "Rahatlamak" },
  { id: 356, en: "An Hour or So", tr: "Bir Saate Kadar" },
  { id: 357, en: "To Go For a Walk", tr: "Yürüyüşe Çıkmak" },
  { id: 358, en: "Perfect", tr: "Mükemmel" },
  { id: 359, en: "Map", tr: "Harita" },
  { id: 360, en: "Guide", tr: "Rehber" },
  { id: 361, en: "Guide Book", tr: "Rehber Kitap" },
  { id: 362, en: "To Go Sightseeing", tr: "Geziye Çıkmak / Bölge Turuna Çıkmak" },
  { id: 363, en: "Art Gallery", tr: "Sanat Galerisi" },
  { id: 364, en: "To Visit Museum", tr: "Müze Ziyaret Etmek" },
  { id: 365, en: "To Look Around", tr: "Bakınmak / Etrafı Seyretmek" },
  { id: 366, en: "To Get Lost", tr: "Kaybolmak" },
  { id: 367, en: "To Take Photos", tr: "Fotoğraf Çekmek" },
  { id: 368, en: "Cash Machine", tr: "Para Çekme Makinesi" },
  { id: 369, en: "Change Dollars into Euro", tr: "Doları Avroya Çevirmek" },
  { id: 370, en: "Exchange Rate", tr: "Döviz Kuru" },
  { id: 371, en: "Commission", tr: "Komisyon" },
  { id: 372, en: "To Charge Someone", tr: "Birini Suçlamak" },
  { id: 373, en: "Envelope", tr: "Zarf" },
  { id: 374, en: "Put a Stamp", tr: "Posta Pulu Koymak" },
  { id: 375, en: "Postman", tr: "Postacı (Erkek)" },
  { id: 376, en: "Postwoman", tr: "Postacı (Kadın)" },
  { id: 377, en: "A Parcel", tr: "Posta / Parsel / Koli" },
  { id: 378, en: "Have a Nice Day", tr: "İyi Günler" },
  { id: 379, en: "Have a Good Day", tr: "İyi Günler" },
  { id: 380, en: "Well Done", tr: "Aferin" },
  { id: 381, en: "Congratulations", tr: "Tebrikler" },
  { id: 382, en: "Good Luck", tr: "İyi Şanslar" },
  { id: 383, en: "Cheers", tr: "Şerefe" },
  { id: 384, en: "To Go Out For", tr: "Dışarı Çıkmak" },
  { id: 385, en: "Come Around For (a Drink)", tr: "İçmek İçin Dışarıda Buluşmak" },
  { id: 386, en: "Invite", tr: "Davet Etmek" },
  { id: 387, en: "Party", tr: "Parti" },
  { id: 388, en: "Great", tr: "Harika" },
  { id: 389, en: "I'd Love To", tr: "Çok İsterim" },
  { id: 390, en: "That Sounds Lovely", tr: "Kulağa Hoş Geliyor" },
  { id: 391, en: "I'm Afraid I Can't", tr: "Korkarım Yapamam" },
  { id: 392, en: "Suggest", tr: "Önermek" },
  { id: 393, en: "Offer", tr: "Ismarlamak" },
  { id: 394, en: "Accept", tr: "Kabul Etmek" },
  { id: 395, en: "Refuse", tr: "Geri Çevirmek" },
  { id: 396, en: "Let Me Pay", tr: "Bırak Ben Ödeyeyim" },
  { id: 397, en: "Let Me Give You a Lift", tr: "Ben Seni Bırakayım" },
  { id: 398, en: "Apologize To Something", tr: "Bir Şey İçin Özür Dilemek" },
  { id: 399, en: "Rude", tr: "Kaba" },
  { id: 400, en: "Lose", tr: "Kaybetmek" },
  { id: 401, en: "Excellent", tr: "Harika" },
  { id: 402, en: "Think", tr: "Düşünmek" },
  { id: 403, en: "Thought", tr: "Düşünce" },
  { id: 404, en: "Agree With Someone", tr: "Biriyle Aynı Fikirde Olmak" },
  { id: 405, en: "Personally", tr: "Kişisel Olarak" },
  { id: 406, en: "A Waste of Money / Time", tr: "Para İsrafı / Zaman Kaybı" },
  { id: 407, en: "Take a Message", tr: "Mesaj / Not Almak" },
  { id: 408, en: "Leave a Message", tr: "Mesaj Bırakmak" },
  { id: 409, en: "Line is Busy / Engaged", tr: "Hat Meşgul" },
  { id: 410, en: "Wrong Number", tr: "Yanlış Numara" }
];

const WORDS_A2_GENEL = [
  { id: 1001, en: "Anniversaries", tr: "Yıl dönümleri" },
  { id: 1002, en: "Architecture", tr: "Mimari" },
  { id: 1003, en: "Beach", tr: "Plaj / Kumsal" },
  { id: 1004, en: "Beautiful", tr: "Güzel" },
  { id: 1005, en: "Believe", tr: "İnanmak" },
  { id: 1006, en: "Border", tr: "Sınır" },
  { id: 1007, en: "Both", tr: "İkisi de / Her ikisi" },
  { id: 1008, en: "Bowl", tr: "Kase" },
  { id: 1009, en: "Cheap", tr: "Ucuz" },
  { id: 1010, en: "Cliffs", tr: "Uçurumlar / Kayalıklar" },
  { id: 1011, en: "Climate", tr: "İklim" },
  { id: 1012, en: "Coast", tr: "Sahil / Kıyı" },
  { id: 1013, en: "Continent", tr: "Kıta" },
  { id: 1014, en: "Cook Lunch", tr: "Öğle Yemeği Pişirmek" },
  { id: 1015, en: "Customers", tr: "Müşteriler" },
  { id: 1016, en: "Delicious", tr: "Lezzetli" },
  { id: 1017, en: "Discuss", tr: "Tartışmak / Görüşmek" },
  { id: 1018, en: "Domestic", tr: "Yerli / Evcil" },
  { id: 1019, en: "Dozens", tr: "Düzinelerce" },
  { id: 1020, en: "Driest", tr: "En kurak" },
  { id: 1021, en: "Dystopic", tr: "Distopik" },
  { id: 1022, en: "East", tr: "Doğu" },
  { id: 1023, en: "Excitement", tr: "Heyecan" },
  { id: 1024, en: "Extensive", tr: "Kapsamlı / Geniş çaplı" },
  { id: 1025, en: "Extremes", tr: "Uç noktalar / Aşırılıklar" },
  { id: 1026, en: "Features", tr: "Özellikler" },
  { id: 1027, en: "Fjords", tr: "Fiyortlar" },
  { id: 1028, en: "Forest", tr: "Orman" },
  { id: 1029, en: "Form", tr: "Biçim / Şekillendirmek" },
  { id: 1030, en: "Gaze", tr: "Gözünü dikip bakmak / Bakış" },
  { id: 1031, en: "Geysers", tr: "Gayzerler" },
  { id: 1032, en: "Glad", tr: "Memnun" },
  { id: 1033, en: "Gold", tr: "Altın" },
  { id: 1034, en: "Gravy", tr: "Et suyu sosu" },
  { id: 1035, en: "Guide", tr: "Rehber / Rehberlik etmek" },
  { id: 1036, en: "Herb", tr: "Bitki / Baharat otu" },
  { id: 1037, en: "High", tr: "Yüksek" },
  { id: 1038, en: "Hill", tr: "Tepe" },
  { id: 1039, en: "Hospitality", tr: "Misafirperverlik" },
  { id: 1040, en: "Idea", tr: "Fikir" },
  { id: 1041, en: "Impressive", tr: "Etkileyici" },
  { id: 1042, en: "Include", tr: "İçermek / Dahil etmek" },
  { id: 1043, en: "Incredible", tr: "İnanılmaz" },
  { id: 1044, en: "Internship", tr: "Staj" },
  { id: 1045, en: "Island", tr: "Ada" },
  { id: 1046, en: "Jewelry", tr: "Mücevher / Takı" },
  { id: 1047, en: "Lake", tr: "Göl" },
  { id: 1048, en: "Landscape", tr: "Manzara / Peyzaj" },
  { id: 1049, en: "Long", tr: "Uzun" },
  { id: 1050, en: "Magnificent", tr: "Muhteşem / Görkemli" },
  { id: 1051, en: "Manager", tr: "Yönetici / Müdür" },
  { id: 1052, en: "Mash", tr: "Püre / Ezmek" },
  { id: 1053, en: "Mountains", tr: "Dağlar" },
  { id: 1054, en: "Narrow", tr: "Dar" },
  { id: 1055, en: "Neighbor", tr: "Komşu" },
  { id: 1056, en: "North", tr: "Kuzey" },
  { id: 1057, en: "Opportunity", tr: "Fırsat" },
  { id: 1058, en: "Peak", tr: "Zirve / Doruk" },
  { id: 1059, en: "Prepare", tr: "Hazırlamak" },
  { id: 1060, en: "Rise", tr: "Yükselmek / Artış" },
  { id: 1061, en: "Sensational", tr: "Sansasyonel / Çarpıcı" },
  { id: 1062, en: "Shape", tr: "Şekil" },
  { id: 1063, en: "Shares", tr: "Paylaşır / Paylar" },
  { id: 1064, en: "Short", tr: "Kısa" },
  { id: 1065, en: "Silver", tr: "Gümüş" },
  { id: 1066, en: "Slang", tr: "Argo" },
  { id: 1067, en: "Sophisticated", tr: "Sofistike / Çok yönlü" },
  { id: 1068, en: "South", tr: "Güney" },
  { id: 1069, en: "Special", tr: "Özel" },
  { id: 1070, en: "Suggest", tr: "Önermek" },
  { id: 1071, en: "Surrounding", tr: "Çevreleyen / Civar" },
  { id: 1072, en: "Take-Away", tr: "Al-götür (Paket servis)" },
  { id: 1073, en: "Think", tr: "Düşünmek" },
  { id: 1074, en: "Topic", tr: "Konu / Başlık" },
  { id: 1075, en: "Tourist Guide", tr: "Turist Rehberi" },
  { id: 1076, en: "Trail", tr: "Patika / İz" },
  { id: 1077, en: "Valley", tr: "Vadi" },
  { id: 1078, en: "Vast", tr: "Uçsuz bucaksız / Çok geniş" },
  { id: 1079, en: "Very Beautiful", tr: "Çok Güzel" },
  { id: 1080, en: "Vinegar", tr: "Sirke" },
  { id: 1081, en: "Volcanoes", tr: "Volkanlar / Yanardağlar" },
  { id: 1082, en: "Waterfalls", tr: "Şelaleler" },
  { id: 1083, en: "Wave", tr: "Dalga" },
  { id: 1084, en: "West", tr: "Batı" },
  { id: 1085, en: "Western", tr: "Batılı / Batıya ait" },
  { id: 1086, en: "Wide", tr: "Geniş" },
  { id: 1087, en: "Wonderful", tr: "Harika / Mükemmel" },
  { id: 1088, en: "Woods", tr: "Ormanlık alan / Koruluk" },
  { id: 1089, en: "Yelling", tr: "Bağırma / Haykırma" },
  { id: 1090, en: "Beaches", tr: "Plajlar / Kumsallar" },
  { id: 1091, en: "Borders", tr: "Sınırlar" },
  { id: 1092, en: "Bowls", tr: "Kaseler" },
  { id: 1093, en: "Climates", tr: "İklimler" },
  { id: 1094, en: "Coasts", tr: "Sahiller / Kıyılar" },
  { id: 1095, en: "Continents", tr: "Kıtalar" },
  { id: 1096, en: "Forests", tr: "Ormanlar" },
  { id: 1097, en: "Forms", tr: "Biçimler / Şekiller" },
  { id: 1098, en: "Gazes", tr: "Bakışlar" },
  { id: 1099, en: "Guides", tr: "Rehberler" },
  { id: 1100, en: "Herbs", tr: "Bitkiler / Baharat otları" },
  { id: 1101, en: "Hills", tr: "Tepeler" },
  { id: 1102, en: "Ideas", tr: "Fikirler" },
  { id: 1103, en: "Internships", tr: "Stajlar" },
  { id: 1104, en: "Islands", tr: "Adalar" },
  { id: 1105, en: "Lakes", tr: "Göller" },
  { id: 1106, en: "Landscapes", tr: "Manzaralar / Peyzajlar" },
  { id: 1107, en: "Managers", tr: "Yöneticiler / Müdürler" },
  { id: 1108, en: "Neighbors", tr: "Komşular" },
  { id: 1109, en: "Opportunities", tr: "Fırsatlar" },
  { id: 1110, en: "Peaks", tr: "Zirveler / Doruklar" },
  { id: 1111, en: "Shapes", tr: "Şekiller" },
  { id: 1112, en: "Topics", tr: "Konular / Başlıklar" },
  { id: 1113, en: "Tourist Guides", tr: "Turist Rehberleri" },
  { id: 1114, en: "Trails", tr: "Patikalar / İzler" },
  { id: 1115, en: "Valleys", tr: "Vadiler" },
  { id: 1116, en: "Waves", tr: "Dalgalar" },
  { id: 1117, en: "Anniversary", tr: "Yıl dönümü" },
  { id: 1118, en: "Cliff", tr: "Uçurum / Kayalık" },
  { id: 1119, en: "Customer", tr: "Müşteri" },
  { id: 1120, en: "Dozen", tr: "Düzine" },
  { id: 1121, en: "Extreme", tr: "Uç nokta / Aşırılık" },
  { id: 1122, en: "Feature", tr: "Özellik" },
  { id: 1123, en: "Fjord", tr: "Fiyort" },
  { id: 1124, en: "Geyser", tr: "Gayzer" },
  { id: 1125, en: "Mountain", tr: "Dağ" },
  { id: 1126, en: "Share", tr: "Paylaşmak / Pay" },
  { id: 1127, en: "Volcano", tr: "Volkan / Yanardağ" },
  { id: 1128, en: "Waterfall", tr: "Şelale" },
  { id: 1129, en: "Wood", tr: "Ormanlık alan / Tahta" },
  { id: 1130, en: "Architect", tr: "Mimar" }
];

const WORDS_A2_GRAMMAR = [
  { id: 5001, en: "This book is not ....... The cover is different.", tr: "mine" },
  { id: 5002, en: "....... went to the grocery store to buy some fresh milk.", tr: "She" },
  { id: 5003, en: "Be careful with that knife! I cut ....... while I was chopping onions yesterday.", tr: "myself" },
  { id: 5004, en: "We need to bring ....... laptops to the presentation tomorrow.", tr: "our" },
  { id: 5005, en: "Their new car is much faster and more comfortable than .......", tr: "ours" },
  { id: 5006, en: "The science teacher gave ....... a lot of homework for the weekend.", tr: "them" },
  { id: 5007, en: "Welcome to the party! Please help ....... to some coffee and cookies.", tr: "yourselves" },
  { id: 5008, en: "Excuse me, is this black jacket .......? I found it on the chair.", tr: "yours" },
  { id: 5009, en: "....... and I have been best friends since we were in elementary school.", tr: "He" },
  { id: 5010, en: "The little cat washed ....... carefully after eating the fish.", tr: "itself" },
  { id: 5011, en: "I lost my contact list. Can you give me ....... phone number again?", tr: "your" },
  { id: 5012, en: "Between you and ......., I don't think this project is going to be successful.", tr: "me" },
  { id: 5013, en: "She was very proud because she built that entire model airplane by .......", tr: "herself" },
  { id: 5014, en: "I forgot my umbrella at home. It is raining heavily, can I borrow .......?", tr: "yours" },
  { id: 5015, en: "....... decided to move to a completely new city next year.", tr: "They" },
  { id: 5016, en: "Those are definitely not my keys; I think they are .......", tr: "hers" },
  { id: 5017, en: "We enjoyed ....... very much at the rock concert last night.", tr: "ourselves" },
  { id: 5018, en: "The weather is so beautiful today. Let ....... go to the park before it gets dark.", tr: "us" },
  { id: 5019, en: "The cute dog wagged ....... tail happily when the owner came back home.", tr: "its" },
  { id: 5020, en: "My computer is broken right now, so I am using ....... to finish my work.", tr: "theirs" },
  { id: 5021, en: "The mechanic fixed the car, but ....... engine is still making a strange noise.", tr: "its" },
  { id: 5022, en: "They painted the whole house by ....... to save a lot of money.", tr: "themselves" },
  { id: 5023, en: "....... are planning to travel to Italy next summer for a long holiday.", tr: "We" },
  { id: 5024, en: "I left my pen on the desk, can I use ....... for a minute?", tr: "yours" },
  { id: 5025, en: "The manager called ....... into the meeting room to discuss the new project.", tr: "us" },
  { id: 5026, en: "He taught ....... how to play the guitar by watching online videos every day.", tr: "himself" },
  { id: 5027, en: "She always forgets ....... passwords when trying to log into the school website.", tr: "her" },
  { id: 5028, en: "....... is raining heavily outside, so you should definitely take a taxi.", tr: "It" },
  { id: 5029, en: "This isn't John's backpack. ....... is dark blue and much bigger.", tr: "His" },
  { id: 5030, en: "Please don't tell ....... the surprise before the birthday party begins.", tr: "her" },
  { id: 5031, en: "We need to submit ....... final reports to the teacher by Friday afternoon.", tr: "our" },
  { id: 5032, en: "I don't need any help, I can carry these heavy boxes by ........", tr: "myself" },
  { id: 5033, en: "....... usually wakes up very early to go for a run in the park.", tr: "He" },
  { id: 5034, en: "My phone battery is completely dead, and my sister refuses to lend me ........", tr: "hers" },
  { id: 5035, en: "The loud music from the neighbor's house kept ....... awake all night.", tr: "them" },
  { id: 5036, en: "Can you please take off ....... shoes before entering the living room?", tr: "your" },
  { id: 5037, en: "The oven is very hot, so be careful not to burn ........", tr: "yourself" },
  { id: 5038, en: "Their garden is beautiful, but I think ....... has more colorful flowers.", tr: "ours" },
  { id: 5039, en: "....... am looking forward to starting my internship at the airline company next month.", tr: "I" },
  { id: 5040, en: "I saw Sarah at the shopping mall yesterday, but I didn't have time to talk to ........", tr: "her" },
  { id: 5041, en: "The dog quickly buried ....... bone in the backyard yesterday morning.", tr: "its" },
  { id: 5042, en: "Welcome to our home, guys! Make ....... comfortable on the couch.", tr: "yourselves" },
  { id: 5043, en: "You brought your lunch, but where is ........ ? I can't find my sandwich anywhere.", tr: "mine" },
  { id: 5044, en: "The pilot explained the safety rules to ....... before the flight took off.", tr: "us" },
  { id: 5045, en: "....... never listen to my advice, even when I know what is best for the team.", tr: "They" },
  { id: 5046, en: "....... brother is studying civil engineering at a university in Istanbul.", tr: "My" },
  { id: 5047, en: "The smart vacuum cleaner can charge ....... automatically when the battery is low.", tr: "itself" },
  { id: 5048, en: "I know this is your seat, but I am not sure which one is ........", tr: "theirs" },
  { id: 5049, en: "Tom was looking for his reading glasses, so I helped ....... find them.", tr: "him" },
  { id: 5050, en: "The passengers must show ....... boarding passes at the gate before boarding.", tr: "their" }
];

const WORDS_A2_DEYIMLER = [
  { id: 6001, en: "A piece of cake", tr: "Çok kolay, çocuk oyuncağı" },
  { id: 6002, en: "Break a leg", tr: "İyi şanslar (Genelde bir sınav veya gösteri öncesi söylenir)" },
  { id: 6003, en: "Under the weather", tr: "Hafif hasta hissetmek, keyifsiz olmak" },
  { id: 6004, en: "Once in a blue moon", tr: "Ayda yılda bir, çok nadir" },
  { id: 6005, en: "Call it a day", tr: "Bugünlük bu kadar yeter, paydos etmek" },
  { id: 6006, en: "So far, so good", tr: "Şu ana kadar her şey yolunda" },
  { id: 6007, en: "Time flies", tr: "Zaman su gibi akıp geçiyor" },
  { id: 6008, en: "Better late than never", tr: "Geç olsun güç olmasın" },
  { id: 6009, en: "Keep an eye on", tr: "Göz kulak olmak, dikkat etmek" },
  { id: 6010, en: "Out of the blue", tr: "Durup dururken, aniden" },
  { id: 6011, en: "Cost an arm and a leg", tr: "Çok pahalı olmak, ateş pahası" },
  { id: 6012, en: "Bite the bullet", tr: "İstemediğin ama mecburi olan bir duruma katlanmak, dişini sıkmak" },
  { id: 6013, en: "Spill the beans", tr: "Ağzındaki baklayı çıkarmak, sırrı vermek" },
  { id: 6014, en: "Hit the sack / Hit the bed", tr: "Kafayı vurup yatmak, uyumaya gitmek" },
  { id: 6015, en: "Raining cats and dogs", tr: "Bardaktan boşanırcasına yağmur yağması" },
  { id: 6016, en: "Pull someone's leg", tr: "Biriyle kafa bulmak, işletmek" },
  { id: 6017, en: "Miss the boat", tr: "Fırsatı kaçırmak" },
  { id: 6018, en: "To be on the same page", tr: "Aynı fikirde olmak, aynı noktada buluşmak" },
  { id: 6019, en: "Let the cat out of the bag", tr: "Sırrı yanlışlıkla ağzından kaçırmak" },
  { id: 6020, en: "Beat around the bush", tr: "Lafı dolandırmak, sadede gelmemek" },
  { id: 6021, en: "No pain, no gain", tr: "Emek olmadan yemek olmaz, zahmetsiz rahmet olmaz" },
  { id: 6022, en: "Rule of thumb", tr: "Genel kural, deneyimlere dayanan pratik kural" },
  { id: 6023, en: "Give a hand", tr: "Yardım eli uzatmak, yardım etmek" },
  { id: 6024, en: "Hold your horses", tr: "Acele etme, sabırlı ol" },
  { id: 6025, en: "In the same boat", tr: "Aynı gemide olmak, aynı zor durumu paylaşmak" },
  { id: 6026, en: "Make up your mind", tr: "Karar vermek" },
  { id: 6027, en: "Take it easy", tr: "Sakin ol, kafana takma" },
  { id: 6028, en: "Catch someone red-handed", tr: "Birini suç işlerken suçüstü yakalamak" },
  { id: 6029, en: "See eye to eye", tr: "Biriyle tamamen aynı görüşte olmak" },
  { id: 6030, en: "Add fuel to the fire", tr: "Yangına körükle gitmek" }
];

const ALL_WORDS_A2 = [...WORDS_A2, ...WORDS_A2_GENEL, ...WORDS_A2_GRAMMAR, ...WORDS_A2_DEYIMLER];
